/**
 * Word (.docx) tools: `word_create` builds a styled document with the `docx`
 * package; `word_read` extracts plain text with an in-house jszip + regex
 * extractor whose behavior is pinned to mammoth 1.11.0's raw-text output by
 * `tests/word-parity.spec.ts`; `word_update` appends paragraphs, bullets,
 * and one table to an existing document via zip surgery.
 */
import type { Context } from '@deepseek-ai/cordis';
export interface WordCreateArgs {
    path: string;
    title?: string;
    paragraphs?: string[];
    bullets?: string[];
    table?: {
        headers: string[];
        rows: string[][];
    };
    overwrite?: boolean;
}
export interface WordUpdateArgs {
    path: string;
    paragraphs?: string[];
    bullets?: string[];
    table?: {
        headers: string[];
        rows: string[][];
    };
}
export declare function wordCreateCounts(args: WordCreateArgs): {
    paragraphs: number;
    cells: number;
};
/**
 * Extract mammoth-compatible plain text from a `word/document.xml` string:
 * every paragraph — body, table cell, hyperlink, or textbox — contributes its
 * runs followed by `\n\n`, including the final and empty paragraphs.
 */
export declare function extractDocxText(documentXml: string): string;
/**
 * Extract structured markdown from a `word/document.xml` string: Title and
 * Heading1-6 render as `#`..`######`, numbered/bullet paragraphs as indented
 * `- ` items, tables as markdown tables, everything else as plain blocks —
 * inline rules identical to {@link extractDocxText}.
 */
export declare function extractDocxMarkdown(documentXml: string): string;
/**
 * Body children for an append, generated by the SAME `docx` package path as
 * word_create (so paragraphs, bullets, and tables come out identical) and
 * extracted from the throwaway document minus its trailing `<w:sectPr>`.
 */
export declare function buildAppendFragment(args: WordUpdateArgs, signal: AbortSignal): Promise<string>;
/**
 * Splice new body children into `word/document.xml`: appended content goes
 * right before the trailing `<w:sectPr>` (page setup must stay the last body
 * child), or before `</w:body>` when the document has no section properties.
 */
export declare function appendBeforeSectPr(documentXml: string, addition: string): string;
export declare function registerWordTools(ctx: Context): () => void;
