/**
 * `word_update` (v0.4.0): append paragraphs, bullets, and one table to an
 * existing .docx. The appended body children are generated by the same
 * `buildDocx` path word_create uses, then spliced into the document's body
 * right before its trailing `<w:sectPr>`; the archive is rewritten atomically.
 */
import type { Context } from '@deepseek-ai/cordis';
export declare function registerWordUpdate(ctx: Context): () => void;
