/**
 * `word_update` (v0.4.0): append paragraphs, bullets, and one table to an
 * existing .docx. The appended body children are generated by the same
 * `buildDocx` path word_create uses, then spliced into the document's body
 * right before its trailing `<w:sectPr>`; the archive is rewritten atomically.
 */

import type { Context } from '@deepseek-ai/cordis'
import { defineTool } from '@deepseek-ai/dsh-tools'
import type { ToolRunContext } from '@deepseek-ai/dsh-tools'
import { atomicWriteFile, loadZipGuarded, readOfficeBuffer, readZipXmlPart, resolveOfficePath } from '../paths.ts'
import { FILE_RESULT_SCHEMA } from './shared.ts'
import { appendBeforeSectPr, buildAppendFragment, wordCreateCounts, type WordUpdateArgs } from './word.ts'

const WORD_UPDATE_OUTPUT = {
  type: 'object',
  additionalProperties: false,
  properties: {
    ...FILE_RESULT_SCHEMA.properties,
    appendedParagraphs: { type: 'integer', required: true },
    appendedBullets: { type: 'integer', required: true },
    appendedTableRows: { type: 'integer', required: true },
  },
} as const

export function registerWordUpdate(ctx: Context): () => void {
  return ctx.tools.register(defineTool({
    name: 'word_update',
    description:
      'Append content to an existing .docx Word document in the session workspace: paragraphs, bullet points, and/or one table are added at the end of the body (in that order), leaving everything already in the file untouched. '
      + 'Bullets reuse the list numbering the document already defines, so they render as bullets in files that have them (files created by word_create always do); documents without list numbering show appended bullets as plain paragraphs. '
      + 'The file is rewritten atomically. Use word_read afterwards to verify.',
    parameters: {
      path: {
        type: 'string',
        required: true,
        description: 'Path to the existing .docx file, relative to the session workspace or absolute inside it.',
      },
      paragraphs: {
        type: 'array',
        items: { type: 'string' },
        description: 'Paragraphs to append in document order. Optional.',
      },
      bullets: {
        type: 'array',
        items: { type: 'string' },
        description: 'Bullet list items appended after the paragraphs. Optional.',
      },
      table: {
        type: 'object',
        additionalProperties: false,
        properties: {
          headers: {
            type: 'array',
            items: { type: 'string' },
            required: true,
            description: 'Table column headers (bold).',
          },
          rows: {
            type: 'array',
            items: { type: 'array', items: { type: 'string' } },
            required: true,
            description: 'Table body rows; each row should match the header column count.',
          },
        },
        description: 'One optional table appended after the text content.',
      },
    },
    output: {
      schema: WORD_UPDATE_OUTPUT,
      render: (_args, value: any) => [{
        type: 'text',
        text: `Appended to Word document ${value.path} (${value.sizeBytes} bytes; ${value.appendedParagraphs} paragraph(s), ${value.appendedBullets} bullet(s), ${value.appendedTableRows} table body row(s) appended).`,
      }],
    },
    presentCall: (args) => ({
      card: 'generic',
      title: `Update ${args.path}`,
      kind: 'edit',
      locations: [{ path: args.path }],
    }),
    async execute(args: WordUpdateArgs, exec: ToolRunContext) {
      const target = await resolveOfficePath(exec, args.path, ['.docx'], true)
      const { paragraphs: paragraphCount, cells } = wordCreateCounts(args)
      if ((args.paragraphs?.length ?? 0) === 0 && (args.bullets?.length ?? 0) === 0 && args.table === undefined) {
        throw new Error('word_update needs at least one of paragraphs, bullets, or table')
      }
      if (paragraphCount > 10_000) throw new Error('too many paragraphs/bullets/table rows (maximum 10000)')
      if (cells > 200_000) throw new Error('too many table cells (maximum 200000)')
      exec.signal.throwIfAborted()

      const { buffer } = await readOfficeBuffer(target.absolute, exec.signal)
      const zip = await loadZipGuarded(buffer, exec.signal)
      const documentXml = await readZipXmlPart(zip, 'word/document.xml', exec.signal)
      if (documentXml === null) {
        throw new Error('the .docx has no word/document.xml part; is this a valid Word file?')
      }
      const fragment = await buildAppendFragment(args, exec.signal)
      const updated = appendBeforeSectPr(documentXml, fragment)
      zip.file('word/document.xml', updated)
      const output = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })
      exec.signal.throwIfAborted()
      const sizeBytes = await atomicWriteFile(target.absolute, output)
      return {
        path: target.display,
        sizeBytes,
        appendedParagraphs: args.paragraphs?.length ?? 0,
        appendedBullets: args.bullets?.length ?? 0,
        appendedTableRows: args.table?.rows.length ?? 0,
      }
    },
  }))
}
